spring:
  datasource:
    url: jdbc:mysql://localhost:3306/url_shortener
    username: root
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
